### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by KaueGuimaraes** [Aayu0710/Mini_notepad#1]
I try to excecute your program and don't work. Error:

```
Traceback (most recent call last):
  File "d:\AnotherProjects\Mini_notepad\Mini_Notepad.py", line 8, in <module>
    img = PhotoImage(file="C:\\Users\\HP\\Downloads\\note.png")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "C:\Users\HP\Downloads\note.png": no such file or directory
```

"C:\Users\HP\Downloads\note.png", "C:\\Users\\HP\\Downloads\\note.png".
Some of the errors can resolve changing the user "C:\\Users\\**HP**\\Downloads\\note.png", it problaby work in your computer cause it try to locate the HP user. You can get the PC's user name doing this:

```
import os
os.getLogin()
```

**Comment by KaueGuimaraes** [comment]
Ok Ok

**Comment by KaueGuimaraes** [comment]
I discovered how to resolve this

**Comment by KaueGuimaraes** [comment]
I will create a fork. The problem is in the lines 8 and 9, if i delete they it work. Here:

```
img = PhotoImage(file="C:\\Users\\HP\\Downloads\\note.png")
root.iconphoto(False,img)
```

**Comment by KaueGuimaraes** [comment]
#12
